### ISSUE TITLE
Gobber Ore

### ISSUE THREAD

**Issue by Lupus56** [ClaudiusMinimus/Survival_in_Chaos#1]
Gobber ore doesn't generate in the overworld or mining dimension.

**Comment by ClaudiusMinimus** [comment]
I am aware and am working on a fix. For now, you will need to spawn a Gobber Ore block to complete the quest, and then you can make a seed. The multiply very quickly, especially if you use the Lilypad of Fertility.

**Comment by ClaudiusMinimus** [comment]
Gobber Ore now generates in 1.16.5-0.21.0

![2021-02-04_16 33 33](https://user-images.githubusercontent.com/17887664/106969138-817fcb00-6707-11eb-87b6-8adcc7b0c8f9.png)
