### ISSUE TITLE
CRassshh

### ISSUE THREAD

**Issue by EvilKilem** [ClaudiusMinimus/Survival_in_Chaos#2]
Flying around looking for lilypads and opened a few new chunks and bam crashola   735ish est

**Comment by ClaudiusMinimus** [comment]
Was it a server or client-side crash?

**Comment by EvilKilem** [comment]
Dont know if it crashed or just froze up....it booted me and was off list for 5 min or so then was back online.  had no more probs after logging back on.

________________________________

**Comment by ClaudiusMinimus** [comment]
Hmm... I've looked at the server and there was no crash report for that timeframe. Without more details it seems maybe you somehow may have lost your connection. If it persists, please open this issue report again and provide as many details as possible.
Thank you,
CM
