### ISSUE TITLE
Datapack errors prevent pack from creating new world

### ISSUE THREAD

**Issue by VallenFrostweaver** [ClaudiusMinimus/Survival_in_Chaos#3]
Launcher: GDLauncher v. 1.0.11 (latest)
Modpack version: 0.22.2
I have much better than recommended hardware on the website. Loading up the pack with 9GB RAM (Max on PC 32)
Loading up the pack is fine. Click single player and chose "Create New World" and I get the below message. I haven't touched any settings besides volume.
![image](https://user-images.githubusercontent.com/13642054/111447916-cf73ef80-8705-11eb-8319-d8f074107518.png)
I tried clicking "Safe Mode" and it hesitates and does nothing and am forced to go back to Title screen. I re-downloaded the pack in case of corruption and the same. I reverted to Modpack version 0.22.0 and it's the same. ):

**Comment by ClaudiusMinimus** [comment]
Sorry to not have gotten back to you. Somehow notifications for this pack got turned off. This issue should be fixed in Survival in Chaos 1.16.5-0.23.0.
Thanks, CM
