### ISSUE TITLE
MC  Server hangs when entering Nether

### ISSUE THREAD

**Issue by mrossi80** [ClaudiusMinimus/Survival_in_Chaos#4]
**MC  Server hangs when entering Nether**
Is not possible to interact anymore with the nether world

**To Reproduce**
- download the pack from Curseforge
- start and create a new singleplayer world
- create a nether portal
- enter the nether portal
- is not possible to interact with the world anymore
- "Waiting for Server" message is on the screen.

**Expected behavior**
- after entering nether, it has to be possible to interact with the world

**Survival in Chaos version (please complete the following information):**
- Survival+in+Chaos+1.16.5-0.22.2
no other modifications.

**Additional context**
I had to "give" nether quartz to me to continue playing.

**Comment by mrossi80** [comment]
**Additional context**

The problem is not present in Survival+in+Chaos+1.16.5-0.21.0, so the regression may have been introduced in 0.22.0 or 0.22.2

**Comment by ClaudiusMinimus** [comment]
Sorry to not have gotten back to you. Somehow notifications for this pack got turned off. I just loaded up a new single-player world and it worked fine. It seems this issue is fixed in Survival in Chaos 1.16.5-0.23.0.
Thanks, CM
