### ISSUE TITLE
SP server stalls while in the Nether.

### ISSUE THREAD

**Issue by kay-el-zed** [ClaudiusMinimus/Survival_in_Chaos#5]
**Describe the bug**
While exploring around in the Nether, the server will completely stall and becomes unresponsive to any in-game actions. Blocks will say "Waiting for server" in their tooltips and the local server will be unresponsive to commands in-game. The local server/client does not crash but has to be forcefully killed - Save & Quit causes the client to hang after the local server has stalled.

**To Reproduce**
1. Launch SiC 0.23.0 and load a singleplayer world.
2. Enter the nether
3. Walk around for a while. Will sometimes take moments to stall and other times will take 20-30 minutes, depending on render distance.
4. No longer possible to interact with the local server. "Waiting for server" appears when looking at blocks.

**Expected behavior**
- To be able to explore the nether without the server stalling.

**Screenshots**
- https://i.imgur.com/HiqjqUg.png

**Survival in Chaos version (please complete the following information):**
- Version: Survival in Chaos 1.16.5-0.23.0
- Have you added any additional mods or made other changes to the pack: N

**Crash Reports and/or logs**
- The local server doesn't crash, so no crash log to attach. Attached last messages logged by client.
- https://pastebin.com/VKzLih9s

**Additional context**
- Happens in both singleplayer and when launching the same world from an external server in multiplayer.
  - Multiplayer server version is 1.16.5-0.23.1
  - When server stalls, players are disconnected due to the timed out connection. 
- Same issue happens when using the `/forge generate 0 0 0 500 minecraft:the_nether` command.
- World was generated in version 0.23.0.
- Could be related to issue #4

**Comment by ClaudiusMinimus** [comment]
What happens if you disable Rats and Ratlantis in a new singleplayer world? Rats has caused issues before and that is why I dropped it from 99 Mods. 

I am in the process of revamping SIC and will be renamed to Create in Chaos (CIC) with about 60 fewer mods. So far it has been very stable with no crashes.

**Comment by kay-el-zed** [comment]
Seems like Rats and Ratlantis was the issue. I've gone nearly an hour in the Nether without any crashes. A bit disappointing but I'm okay with disabling them. Thanks for the quick response!

**Comment by ClaudiusMinimus** [comment]
Thank you for letting me know! I will push out a new release with Rats removed this coming week.
